// ============ HERO DATA ============
// (Lifted from original wheel-of-fate.html — full roster with role/attr/lane/complexity)
window.HEROES = [
  {name:"Anti-Mage",attr:"agi",roles:["Carry"],lane:"Safelane",complexity:1,tag:"The Magic Killer"},
  {name:"Axe",attr:"str",roles:["Offlane"],lane:"Offlane",complexity:1,tag:"The Mad Headsman"},
  {name:"Bane",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:2,tag:"Atropos, Bringer of Dreams"},
  {name:"Bloodseeker",attr:"agi",roles:["Carry","Offlane"],lane:"Safelane",complexity:1,tag:"Strygwyr, The Thirst"},
  {name:"Crystal Maiden",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:1,tag:"Rylai of the Ice"},
  {name:"Drow Ranger",attr:"agi",roles:["Carry"],lane:"Safelane",complexity:1,tag:"Traxex, The Marksman"},
  {name:"Earthshaker",attr:"str",roles:["Support","Offlane"],lane:"Roaming",complexity:2,tag:"Raigor of the Stone"},
  {name:"Juggernaut",attr:"agi",roles:["Carry","Mid"],lane:"Safelane",complexity:1,tag:"Yurnero, Blade of the Isle"},
  {name:"Mirana",attr:"agi",roles:["Mid","Support"],lane:"Midlane",complexity:2,tag:"Princess of the Moon"},
  {name:"Morphling",attr:"agi",roles:["Carry","Mid"],lane:"Safelane",complexity:3,tag:"Morphling, The Shifter"},
  {name:"Shadow Fiend",attr:"agi",roles:["Mid"],lane:"Midlane",complexity:2,tag:"Nevermore the Soul Reaper"},
  {name:"Phantom Lancer",attr:"agi",roles:["Carry"],lane:"Safelane",complexity:2,tag:"Azwraith of the Coriltain"},
  {name:"Puck",attr:"uni",roles:["Mid"],lane:"Midlane",complexity:3,tag:"The Faerie Dragon"},
  {name:"Pudge",attr:"str",roles:["Support","Offlane"],lane:"Roaming",complexity:2,tag:"The Butcher of Fellstad"},
  {name:"Razor",attr:"agi",roles:["Mid","Offlane","Carry"],lane:"Midlane",complexity:1,tag:"The Lightning Revenant"},
  {name:"Sand King",attr:"uni",roles:["Offlane","Support"],lane:"Offlane",complexity:2,tag:"Crixalis of the Dune"},
  {name:"Storm Spirit",attr:"int",roles:["Mid"],lane:"Midlane",complexity:3,tag:"Raijin Thunderkeg"},
  {name:"Sven",attr:"str",roles:["Carry","Offlane"],lane:"Safelane",complexity:1,tag:"The Rogue Knight"},
  {name:"Tiny",attr:"str",roles:["Mid","Support","Offlane"],lane:"Midlane",complexity:2,tag:"The Stone Giant"},
  {name:"Vengeful Spirit",attr:"agi",roles:["Support","Hard Support"],lane:"Lane support",complexity:1,tag:"Shendelzare, The Avenger"},
  {name:"Windranger",attr:"uni",roles:["Mid","Support","Offlane"],lane:"Midlane",complexity:2,tag:"Lyralei of the Wind"},
  {name:"Zeus",attr:"int",roles:["Mid"],lane:"Midlane",complexity:1,tag:"Lord of Heaven"},
  {name:"Kunkka",attr:"str",roles:["Mid","Offlane","Carry"],lane:"Midlane",complexity:2,tag:"Admiral of the Claddish"},
  {name:"Lina",attr:"uni",roles:["Mid","Support"],lane:"Midlane",complexity:1,tag:"The Slayer"},
  {name:"Lion",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:1,tag:"The Demon Witch"},
  {name:"Shadow Shaman",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:1,tag:"Rhasta, the Shaman"},
  {name:"Slardar",attr:"str",roles:["Offlane","Carry"],lane:"Offlane",complexity:1,tag:"Slithereen Guard"},
  {name:"Tidehunter",attr:"str",roles:["Offlane"],lane:"Offlane",complexity:1,tag:"Leviathan of the Deep"},
  {name:"Witch Doctor",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:1,tag:"Zharvakko"},
  {name:"Lich",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:1,tag:"Ethreain of the Ice"},
  {name:"Riki",attr:"agi",roles:["Carry","Support"],lane:"Safelane",complexity:1,tag:"The Stealth Assassin"},
  {name:"Enigma",attr:"int",roles:["Offlane","Support"],lane:"Offlane",complexity:2,tag:"The Void Anomaly"},
  {name:"Tinker",attr:"int",roles:["Mid"],lane:"Midlane",complexity:3,tag:"Boush of Violet Plateau"},
  {name:"Sniper",attr:"agi",roles:["Carry","Mid"],lane:"Safelane",complexity:1,tag:"Kardel Sharpeye"},
  {name:"Necrophos",attr:"int",roles:["Mid","Offlane"],lane:"Midlane",complexity:2,tag:"Rotund'jere, The Necromancer"},
  {name:"Warlock",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:1,tag:"Demnok Lannik"},
  {name:"Beastmaster",attr:"str",roles:["Offlane"],lane:"Offlane",complexity:2,tag:"Karroch of the Hunt"},
  {name:"Queen of Pain",attr:"int",roles:["Mid"],lane:"Midlane",complexity:2,tag:"Akasha, The Succubus"},
  {name:"Venomancer",attr:"agi",roles:["Offlane","Support"],lane:"Offlane",complexity:1,tag:"Lesale Deathbringer"},
  {name:"Faceless Void",attr:"agi",roles:["Carry"],lane:"Safelane",complexity:2,tag:"Darkterror, Beyond Time"},
  {name:"Wraith King",attr:"str",roles:["Carry"],lane:"Safelane",complexity:1,tag:"Ostarion of the Skeleton Throne"},
  {name:"Death Prophet",attr:"int",roles:["Mid","Offlane"],lane:"Midlane",complexity:1,tag:"Krobelus the Witch"},
  {name:"Phantom Assassin",attr:"agi",roles:["Carry"],lane:"Safelane",complexity:1,tag:"Mortred of the Veiled Sisters"},
  {name:"Pugna",attr:"int",roles:["Mid","Support"],lane:"Midlane",complexity:2,tag:"Oblivion's Heir"},
  {name:"Templar Assassin",attr:"agi",roles:["Mid"],lane:"Midlane",complexity:2,tag:"Lanaya, The Refracted One"},
  {name:"Viper",attr:"agi",roles:["Mid","Offlane"],lane:"Midlane",complexity:1,tag:"The Netherdrake"},
  {name:"Luna",attr:"agi",roles:["Carry"],lane:"Safelane",complexity:1,tag:"The Moon Rider"},
  {name:"Dragon Knight",attr:"str",roles:["Mid","Offlane","Carry"],lane:"Midlane",complexity:1,tag:"Davion, Knight of Dragons"},
  {name:"Dazzle",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:2,tag:"Shadow Priest of the Dezun"},
  {name:"Clockwerk",attr:"str",roles:["Offlane","Support"],lane:"Roaming",complexity:2,tag:"Rattletrap, The Cogwright"},
  {name:"Leshrac",attr:"int",roles:["Mid","Offlane"],lane:"Midlane",complexity:2,tag:"Tormented Soul"},
  {name:"Nature's Prophet",attr:"int",roles:["Mid","Offlane","Carry"],lane:"Splitpush",complexity:2,tag:"Furion of the Druidic Caste"},
  {name:"Lifestealer",attr:"str",roles:["Carry"],lane:"Safelane",complexity:1,tag:"N'aix, The Infested"},
  {name:"Dark Seer",attr:"int",roles:["Offlane"],lane:"Offlane",complexity:2,tag:"Ish'Kafel, The Seer"},
  {name:"Clinkz",attr:"agi",roles:["Carry"],lane:"Safelane",complexity:2,tag:"The Bone Fletcher"},
  {name:"Omniknight",attr:"str",roles:["Support","Offlane"],lane:"Lane support",complexity:1,tag:"Purist Thunderwrath"},
  {name:"Enchantress",attr:"int",roles:["Support","Offlane"],lane:"Lane support",complexity:2,tag:"Aiushtha, Wisp of the Wild"},
  {name:"Huskar",attr:"str",roles:["Mid","Carry","Offlane"],lane:"Midlane",complexity:1,tag:"The Sacred Warrior"},
  {name:"Night Stalker",attr:"str",roles:["Offlane","Mid"],lane:"Offlane",complexity:1,tag:"Balanar, The Dark One"},
  {name:"Broodmother",attr:"agi",roles:["Mid","Offlane"],lane:"Midlane",complexity:3,tag:"Black Arachnia"},
  {name:"Bounty Hunter",attr:"agi",roles:["Support"],lane:"Roaming",complexity:1,tag:"Gondar of Aziyog"},
  {name:"Weaver",attr:"agi",roles:["Carry","Mid","Offlane"],lane:"Safelane",complexity:2,tag:"Skitskurr, The Weaver"},
  {name:"Jakiro",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:1,tag:"The Twin Head Dragon"},
  {name:"Batrider",attr:"uni",roles:["Mid","Offlane"],lane:"Offlane",complexity:2,tag:"Jin'zakk of the Yama Raskav"},
  {name:"Chen",attr:"int",roles:["Support"],lane:"Jungle",complexity:3,tag:"Holy Knight of the Fold"},
  {name:"Spectre",attr:"agi",roles:["Carry"],lane:"Safelane",complexity:2,tag:"Mercurial of the Spectral Plane"},
  {name:"Ancient Apparition",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:2,tag:"Kaldr, The First Frost"},
  {name:"Doom",attr:"str",roles:["Offlane","Mid"],lane:"Offlane",complexity:2,tag:"Lucifer, The Fallen"},
  {name:"Ursa",attr:"agi",roles:["Carry","Offlane"],lane:"Safelane",complexity:1,tag:"Ulfsaar, Warrior of the Bear"},
  {name:"Spirit Breaker",attr:"str",roles:["Support","Offlane"],lane:"Roaming",complexity:1,tag:"Barathrum, Born of Wind"},
  {name:"Gyrocopter",attr:"agi",roles:["Carry","Support"],lane:"Safelane",complexity:2,tag:"Aurel of the Keen Folk"},
  {name:"Alchemist",attr:"str",roles:["Carry","Mid","Offlane"],lane:"Safelane",complexity:2,tag:"Razzil Darkbrew"},
  {name:"Invoker",attr:"uni",roles:["Mid"],lane:"Midlane",complexity:3,tag:"Kael, The Magus Cataclysm"},
  {name:"Silencer",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:1,tag:"Nortrom, of the Vault"},
  {name:"Outworld Destroyer",attr:"int",roles:["Mid","Carry"],lane:"Midlane",complexity:2,tag:"Harbinger of the Outworld"},
  {name:"Lycan",attr:"uni",roles:["Offlane","Carry"],lane:"Offlane",complexity:2,tag:"Banehallow, Lord of Wolves"},
  {name:"Brewmaster",attr:"uni",roles:["Offlane","Mid"],lane:"Offlane",complexity:3,tag:"Mangix, The Brewmaster"},
  {name:"Shadow Demon",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:2,tag:"Eredar of the Burning Legion"},
  {name:"Lone Druid",attr:"uni",roles:["Carry","Offlane"],lane:"Safelane",complexity:3,tag:"Sylla of the Forest"},
  {name:"Chaos Knight",attr:"str",roles:["Carry","Offlane"],lane:"Safelane",complexity:1,tag:"Nessaj, The Chaos Knight"},
  {name:"Meepo",attr:"uni",roles:["Mid","Carry"],lane:"Midlane",complexity:3,tag:"The Geomancer"},
  {name:"Treant Protector",attr:"str",roles:["Support","Hard Support"],lane:"Lane support",complexity:2,tag:"Rooftrellen, The Treant"},
  {name:"Ogre Magi",attr:"uni",roles:["Support","Hard Support"],lane:"Lane support",complexity:1,tag:"Aggron Stonebreak"},
  {name:"Undying",attr:"str",roles:["Support","Offlane"],lane:"Lane support",complexity:1,tag:"Dirge of the Almuric"},
  {name:"Rubick",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:3,tag:"Grand Magus of Aghanim"},
  {name:"Disruptor",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:2,tag:"Thrall of the Stormcrafter"},
  {name:"Nyx Assassin",attr:"agi",roles:["Support"],lane:"Roaming",complexity:2,tag:"Anub'arak of the Nyx"},
  {name:"Naga Siren",attr:"agi",roles:["Carry"],lane:"Safelane",complexity:3,tag:"Slithice, Queen of Slithereen"},
  {name:"Keeper of the Light",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:3,tag:"Ezalor of the Primordial"},
  {name:"Io",attr:"uni",roles:["Support"],lane:"Lane support",complexity:3,tag:"The Wisp, Fundamental"},
  {name:"Visage",attr:"uni",roles:["Offlane","Mid"],lane:"Offlane",complexity:3,tag:"Necro'lic of Avernus"},
  {name:"Slark",attr:"agi",roles:["Carry"],lane:"Safelane",complexity:2,tag:"Murloc Nightcrawler"},
  {name:"Medusa",attr:"agi",roles:["Carry"],lane:"Safelane",complexity:2,tag:"Gorgon, The Stone Gaze"},
  {name:"Troll Warlord",attr:"agi",roles:["Carry"],lane:"Safelane",complexity:1,tag:"Jah'rakal of the Hazhadal"},
  {name:"Centaur Warrunner",attr:"str",roles:["Offlane"],lane:"Offlane",complexity:1,tag:"Bradwarden, The Khan"},
  {name:"Magnus",attr:"uni",roles:["Mid","Offlane","Support"],lane:"Midlane",complexity:2,tag:"Magnoceros, Last of the Magnoceri"},
  {name:"Timbersaw",attr:"str",roles:["Offlane","Mid"],lane:"Offlane",complexity:2,tag:"Rizzrack of Augury"},
  {name:"Bristleback",attr:"str",roles:["Offlane","Carry"],lane:"Offlane",complexity:1,tag:"Rigwarl, The Bristleback"},
  {name:"Tusk",attr:"str",roles:["Support","Offlane"],lane:"Roaming",complexity:2,tag:"Ymir, The Trapper"},
  {name:"Skywrath Mage",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:2,tag:"Dragonus, Mage of Ghastly Eyrie"},
  {name:"Abaddon",attr:"uni",roles:["Support","Offlane","Carry"],lane:"Lane support",complexity:1,tag:"Lord of Avernus"},
  {name:"Elder Titan",attr:"str",roles:["Support","Hard Support"],lane:"Lane support",complexity:2,tag:"Tauros Elektrov"},
  {name:"Legion Commander",attr:"uni",roles:["Offlane","Mid"],lane:"Offlane",complexity:1,tag:"Tresdin of the Bronze Legion"},
  {name:"Techies",attr:"int",roles:["Support","Mid"],lane:"Lane support",complexity:3,tag:"Spleen, Sniper & Donk"},
  {name:"Ember Spirit",attr:"uni",roles:["Mid","Carry"],lane:"Midlane",complexity:3,tag:"Xin, The Burning Cinder"},
  {name:"Earth Spirit",attr:"str",roles:["Support","Offlane"],lane:"Roaming",complexity:3,tag:"Kaolin of the Earthen"},
  {name:"Underlord",attr:"str",roles:["Offlane"],lane:"Offlane",complexity:1,tag:"Vrogros, of the Abyssal Horde"},
  {name:"Terrorblade",attr:"agi",roles:["Carry"],lane:"Safelane",complexity:2,tag:"The Demon Marauder"},
  {name:"Phoenix",attr:"uni",roles:["Support","Offlane"],lane:"Lane support",complexity:2,tag:"Icarus, The Sunbird"},
  {name:"Oracle",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:3,tag:"Nerif of the Eternal Garden"},
  {name:"Winter Wyvern",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:2,tag:"Auroth, The Heroic Saga"},
  {name:"Arc Warden",attr:"agi",roles:["Carry","Mid"],lane:"Safelane",complexity:3,tag:"Zet, The Arc Warden"},
  {name:"Monkey King",attr:"agi",roles:["Carry","Mid","Offlane"],lane:"Safelane",complexity:2,tag:"Sun Wukong, The Great Sage"},
  {name:"Dark Willow",attr:"uni",roles:["Support","Hard Support"],lane:"Lane support",complexity:2,tag:"Mireska Sunbreeze"},
  {name:"Pangolier",attr:"uni",roles:["Mid","Offlane","Carry"],lane:"Midlane",complexity:3,tag:"Donté Panlin, Swashbuckler"},
  {name:"Grimstroke",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:2,tag:"Ink Wraith of Bleeding Hollow"},
  {name:"Hoodwink",attr:"agi",roles:["Support","Mid"],lane:"Lane support",complexity:2,tag:"The Sharpshooter Sciuridae"},
  {name:"Void Spirit",attr:"uni",roles:["Mid","Offlane"],lane:"Midlane",complexity:2,tag:"Inai, The Adversary"},
  {name:"Snapfire",attr:"str",roles:["Support","Hard Support"],lane:"Lane support",complexity:2,tag:"Beatrix Snapfire"},
  {name:"Mars",attr:"str",roles:["Offlane","Mid"],lane:"Offlane",complexity:1,tag:"God of War"},
  {name:"Dawnbreaker",attr:"str",roles:["Offlane","Support","Mid"],lane:"Offlane",complexity:1,tag:"Valora, Forged in Dawn"},
  {name:"Marci",attr:"uni",roles:["Support","Offlane","Carry"],lane:"Lane support",complexity:2,tag:"Marci, Fist of the Lotus"},
  {name:"Primal Beast",attr:"str",roles:["Offlane","Mid"],lane:"Offlane",complexity:1,tag:"The Caged Brute"},
  {name:"Muerta",attr:"int",roles:["Carry","Mid","Support"],lane:"Safelane",complexity:2,tag:"The Revenant of the Realm Between"},
  {name:"Ringmaster",attr:"int",roles:["Support","Hard Support"],lane:"Lane support",complexity:2,tag:"Master of the Wandering Carnival"},
  {name:"Kez",attr:"agi",roles:["Carry","Mid"],lane:"Safelane",complexity:2,tag:"The Twin Blades of Falconwing"}
];

// Late-game items (terminal builds — components excluded)
window.ITEMS = ["Black King Bar","Aghanim's Blessing","Manta Style","Heaven's Halberd","Eye of Skadi","Daedalus","Butterfly","Mjollnir","Monkey King Bar","Satanic","Abyssal Blade","Heart of Tarrasque","Assault Cuirass","Shiva's Guard","Refresher Orb","Linken's Sphere","Bloodthorn","Scythe of Vyse","Octarine Core","Moon Shard","Divine Rapier","Radiance","Hurricane Pike","Silver Edge","Nullifier","Lotus Orb","Bloodstone","Overwhelming Blink","Swift Blink","Arcane Blink","Khanda","Wraith Pact","Disperser","Revenant's Brooch","Harpoon","Helm of the Overlord","Yasha and Kaya","Kaya and Sange","Boots of Travel","Boots of Bearing","Guardian Greaves"];

window.SKILL_BUILDS = ["Max Q first","Max W first","Max E first","Value W, max Q","Value E, max Q","Mixed leveling"];
window.COMPLEXITY_LABELS = {1:"★ Easy", 2:"★★ Medium", 3:"★★★ Hard"};
window.ATTR_NAMES = {str:"Strength", agi:"Agility", int:"Intelligence", uni:"Universal"};
